# -*- coding: utf-8 -*-
"""4_20101470_MD_Jubayer_Hossain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCifc8wlkqGtTi76utYGs4Rkii1vM5Fp
"""

import numpy as np
import random as rd


class GeneticAlgorithmGenerator:

    def __init__(self, path):
        with open(path, 'r', encoding='utf-8') as f:
            self.lines = [line.strip().split() for line in f.readlines()]
        self.n = int(self.lines[0][0])
        self.run = int(self.lines[0][1])
        self.runs = {key: value for (key, value) in self.lines[1:]}
        self.initial_population = 40
        self.populations = np.random.randint(
            0, 2, (self.initial_population, self.n))

    def __str__(self):
        return f"{list(self.runs.keys())}\n{self.genetic()}"

    def mutate(self, new_child):
        mutation_idx = rd.randint(0, self.n - 1)
        new_child[mutation_idx] = 1 if new_child[mutation_idx] == 0 else 0
        return new_child

    def crossover(self, x, y):
        idx = rd.randint(0, self.n)
        return np.concatenate((x[:idx], y[idx:]))

    def select(self):
        random_index = [rd.randint(0, self.initial_population - 1)
                        for _ in range(self.initial_population)]
        idx_1, idx_2 = rd.choices(random_index, k=2)
        return self.populations[idx_1], self.populations[idx_2]

    def fitness(self, populations):
        combination = []
        run = 0
        for population in populations:
            first_list = population.tolist()
            second_list = self.runs.items()
            run = 0
            for first, second in zip(first_list, second_list):
                if first == 1:
                    run = run + int(second[1])
            combination.append(run)
        return combination

    def genetic(self):
        for _ in range(500):
            for _ in range(self.initial_population):
                chromosome_1, chromosome_2 = self.select()
                chromosome_child = self.crossover(chromosome_1, chromosome_2)
                chromosome_child = self.mutate(chromosome_child)
                if self.fitness([chromosome_child])[0] == self.run:
                    return "".join(map(str, chromosome_child.tolist()))
        return -1


initiate = GeneticAlgorithmGenerator("input.txt")
print(initiate)
