# -*- coding: utf-8 -*-
"""4_20101470_MD_Jubayer_Hossain.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P_-bCVSuqukBiQ8dta--FHPWxrAStk6-
"""

def aStarAlgo(start_node, stop_node):
         
        open_set = set(start_node) 
        closed_set = set()
        g = {} 
        parents = {}
        g[start_node] = 0
        parents[start_node] = start_node
         
        while len(open_set) > 0:
            n = None
            for v in open_set:
                if n == None or g[v] + heuristic(v) < g[n] + heuristic(n):
                    n = v

            if n == stop_node or Graph_nodes[n] == None:
                pass
            else:
                for (m, weight) in get_neighbors(n):
                    if m not in open_set and m not in closed_set:
                        open_set.add(m)
                        parents[m] = n
                        g[m] = g[n] + weight
      
                    else:
                        if g[m] > g[n] + weight:
                            g[m] = g[n] + weight
                            parents[m] = n
                            if m in closed_set:
                                closed_set.remove(m)
                                open_set.add(m)
 
            if n == None:
                print('Path does not exist!')
                return None
            if n == stop_node:
                path = []
 
                while parents[n] != n:
                    path.append(n)
                    n = parents[n]
 
                path.append(start_node)
                path.reverse()
                return path

            open_set.remove(n)
            closed_set.add(n)
 
        print('Path does not exist!')
        return None
         
def get_neighbors(v):
    if v in Graph_nodes:
        return Graph_nodes[v]
    else:
        return None

def heuristic(n):
        H_dist = {
     
            'A': 366,
            'E': 374,
            'B': 380,
            'Z': 0,
            'I': 77,
            'C': 329,
            'G': 244,
            'L': 241,
            'V': 242,
            'S': 160,
            'R': 193,
            'U': 253,
            'O': 178,
            'P': 98,
            'D': 80,
            'T': 161,
            'N': 151,
            'H': 199,
            'Q': 226,
            'F': 234 
        }
 
        return H_dist[n]
 
Graph_nodes = {
    
    'A': [('E', 75), ("U", 140), ('C', 118)],
    'E': [("A", 75), ("B", 71)],
    'B': [("E", 71), ("U", 151)],
    'Z': [('P', 101), ('O', 211), ('I', 90), ('D', 85)],
    'I': [('Z', 90)],
    'C': [('A', 118), ('G', 111)],
    'G': [('C', 111), ("L", 70)],
    'P': [('R', 97), ('S', 138), ('Z', 101)],
    'D': [('Z', 85), ('H', 142), ('N', 98)],
    'T': [('N', 86)],
    'L': [('G', 70), ('V', 75)],  
    'V':  [('L', 75), ('S', 120)],
    'S': [('V', 120), ('R', 146), ('P', 138)],
    'R': [('U', 80), ('P', 97), ('S', 146)],  
    'U': [('B', 151), ('A', 140), ('R', 80), ('O', 99)],  
    'O':  [('U', 99), ('Z', 211)],
    'N':  [('T', 86), ('D', 98)],
    'H':  [('D', 142), ('Q', 92)],
    'Q':  [('F', 87), ('H', 92)],
    'F': [('Q', 87)]
}

converted_graph = {
    'A':'Arad',
    'Z':'Bucharest',
    'S':'Craiova',
    'T':'Eforie',
    'O':'Fagaras',
   'V':'Dobreta',
    'N':'Hirsova',
    'Q':'lasi',
    'G':'Lugoj',
    'L':'Mehadia',
    'F':'Neamt',
    'B':'Oradea',
    'P':'Pitesti',
    'R':'Rimnicu',
    'C':'Timisoara',
    'D':'Urziceni',
    'H':'Vaslui',
    'E':'Zerind',
    'U': 'Sibiu'
}

path = aStarAlgo('A', 'Z')
output = []
for i in path:
    output.append(converted_graph[i])
print("Path:",' -> '.join(output))
idx = [1, 2, 1, 2]
total_dis = 0
for city in range(len(path)-1):
    total_dis += Graph_nodes[path[city]][idx[city]][1]

print('Total distance : ', total_dis, 'km')
